/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificationIndexRouteImport } from './routes/verification.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerificationJobIdRouteImport } from './routes/verification.$jobId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AgenciesAgencyShortRouteImport } from './routes/agencies.$agencyShort'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminPortalsRouteImport } from './routes/admin.portals'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationIndexRoute = VerificationIndexRouteImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgenciesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerificationJobIdRoute = VerificationJobIdRouteImport.update({
  id: '/verification/$jobId',
  path: '/verification/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AgenciesAgencyShortRoute = AgenciesAgencyShortRouteImport.update({
  id: '/$agencyShort',
  path: '/$agencyShort',
  getParentRoute: () => AgenciesRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortalsRoute = AdminPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/portals': typeof AdminPortalsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/agencies/$agencyShort': typeof AgenciesAgencyShortRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/verification/$jobId': typeof VerificationJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/verification/': typeof VerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/portals': typeof AdminPortalsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/agencies/$agencyShort': typeof AgenciesAgencyShortRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/verification/$jobId': typeof VerificationJobIdRoute
  '/admin': typeof AdminIndexRoute
  '/agencies': typeof AgenciesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/verification': typeof VerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/portals': typeof AdminPortalsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/agencies/$agencyShort': typeof AgenciesAgencyShortRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/verification/$jobId': typeof VerificationJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/verification/': typeof VerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/privacy'
    | '/register'
    | '/search'
    | '/sign-in'
    | '/status'
    | '/terms'
    | '/admin/agencies'
    | '/admin/alerts'
    | '/admin/login'
    | '/admin/portals'
    | '/admin/system-health'
    | '/agencies/$agencyShort'
    | '/jobs/$jobId'
    | '/verification/$jobId'
    | '/admin/'
    | '/agencies/'
    | '/jobs/'
    | '/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/search'
    | '/sign-in'
    | '/status'
    | '/terms'
    | '/admin/agencies'
    | '/admin/alerts'
    | '/admin/login'
    | '/admin/portals'
    | '/admin/system-health'
    | '/agencies/$agencyShort'
    | '/jobs/$jobId'
    | '/verification/$jobId'
    | '/admin'
    | '/agencies'
    | '/jobs'
    | '/verification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/privacy'
    | '/register'
    | '/search'
    | '/sign-in'
    | '/status'
    | '/terms'
    | '/admin/agencies'
    | '/admin/alerts'
    | '/admin/login'
    | '/admin/portals'
    | '/admin/system-health'
    | '/agencies/$agencyShort'
    | '/jobs/$jobId'
    | '/verification/$jobId'
    | '/admin/'
    | '/agencies/'
    | '/jobs/'
    | '/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgenciesRoute: typeof AgenciesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  VerificationJobIdRoute: typeof VerificationJobIdRoute
  VerificationIndexRoute: typeof VerificationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/': {
      id: '/verification/'
      path: '/verification'
      fullPath: '/verification/'
      preLoaderRoute: typeof VerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verification/$jobId': {
      id: '/verification/$jobId'
      path: '/verification/$jobId'
      fullPath: '/verification/$jobId'
      preLoaderRoute: typeof VerificationJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/agencies/$agencyShort': {
      id: '/agencies/$agencyShort'
      path: '/$agencyShort'
      fullPath: '/agencies/$agencyShort'
      preLoaderRoute: typeof AgenciesAgencyShortRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portals': {
      id: '/admin/portals'
      path: '/portals'
      fullPath: '/admin/portals'
      preLoaderRoute: typeof AdminPortalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPortalsRoute: typeof AdminPortalsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPortalsRoute: AdminPortalsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgenciesRouteChildren {
  AgenciesAgencyShortRoute: typeof AgenciesAgencyShortRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesAgencyShortRoute: AgenciesAgencyShortRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgenciesRoute: AgenciesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  VerificationJobIdRoute: VerificationJobIdRoute,
  VerificationIndexRoute: VerificationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
